name: Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{vars.NODE_VERSION}}
      - uses: tree-sitter/parser-update-action@v1.1
        with:
          parent-name: cpp
          language-name: cuda
